In [21]:
import pandas as pd

In [22]:
df = pd.read_excel(r"C:\Users\USER\Desktop\Pandas Tutorial\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [23]:
df.drop_duplicates()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [24]:
df["Last_Name"] = df["Last_Name"].str.strip("/_-123..")

In [25]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [26]:
df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]','', regex = True)

In [27]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [28]:
df["Phone_Number"].apply(lambda x : str(x))

0     1235455421
1     1236439775
2            nan
3     1235432345
4     8766783469
5     3047622467
6            nan
7     8766783469
8             Na
9     1235455421
10           nan
11           nan
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           nan
18            Na
19    8766783469
20    8766783469
Name: Phone_Number, dtype: str

In [29]:
df["Phone_Number"] = df["Phone_Number"].str.replace('nan','')
df["Phone_Number"] = df["Phone_Number"].str.replace('Na','')
df["Phone_Number"] = df["Phone_Number"].str.replace('NaN','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [30]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x : str(x))
df["Phone_Number"] = df["Phone_Number"].apply(lambda x : x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,--,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [31]:
df[["Street Address","State","Zip Code"]] = df["Address"].str.split(',',n = 2, expand = True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,93 West Main Street,NaN,NaN
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,nan--,1209 South Street,No,No,False,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,False,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN,True,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,--,N/a,N/a,Yes,True,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,NaN
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,NaN

In [32]:
df = df.drop(columns = [ 'Address', 'Not_Useful_Column'], errors = 'ignore')

In [33]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,NaN,NaN
2,1003,Walter,White,nan--,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,nan--,No,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,--,Yes,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,nan--,Yes,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,nan--,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,nan--,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,--,N/a,Y,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,NaN
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,NaN

In [34]:
df.replace(['--','N/a','NaN','nan--'],'')

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,NaN,NaN
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,,No,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,Yes,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,,Y,,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,NaN
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,NaN

In [35]:
df = df[df["Do_Not_Contact"] != 'Y']
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,NaN
2,1003,Walter,White,nan--,N,NaN,298 Drugs Driveway,NaN,NaN
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
6,1007,Jeff,Winger,nan--,No,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,--,Yes,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,nan--,Yes,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,nan--,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,nan--,Y,NaN,3498 Super Lane,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,NaN
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,NaN

In [36]:
df = df.replace(['--','N/a','NaN','nan--'],'')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,NaN
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,NaN,NaN
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
6,1007,Jeff,Winger,,No,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,Yes,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,NaN
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,NaN

In [37]:
df["Paying Customer"] = df["Paying Customer"].str.replace('Yes','Y')
df["Paying Customer"] = df["Paying Customer"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,NaN
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,NaN,NaN
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN,NaN
6,1007,Jeff,Winger,,N,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,NaN
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,NaN

In [41]:
df = df.fillna('')

In [44]:
for x in df.index:
    if df.loc[ x, "Phone_Number"] == '':
        df.drop(x , inplace = True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [45]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [46]:
df = df.drop(columns ='Do_Not_Contact')

In [47]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,Y,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,Y,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-3469,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,Y,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,Y,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,Y,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-3469,Y,910 Tatooine Road,Tatooine,

In [48]:
df.reset_index( drop = True)

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Street Address,State,Zip Code
0,1001,Frodo,Baggins,123-545-5421,Y,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,Y,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,Y,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,Y,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,Y,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,Y,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,Y,910 Tatooine Road,Tatooine,
10,1020,Anakin,Skywalker,876-678-3469,Y,910 Tatooine Road,Tatooine,

In [49]:
df.to_csv("customer_list_clean.csv", index=False)